# Generated by Django 3.2.9 on 2022-05-09 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_num', models.SmallIntegerField(default=4, unique=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)])),
                ('width', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)])),
                ('depth', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='HandleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laminate_type', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Overprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overprint_type', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2')], default='A1', max_length=5)),
                ('grammage', models.CharField(choices=[('100', '100'), ('150', '150'), ('200', '200')], default='150', max_length=5)),
                ('paper_type', models.CharField(choices=[('coated', 'powlekany'), ('uncoated', 'niepowlekany')], default='uncoated', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=100)),
                ('component_id', models.IntegerField()),
                ('price_from', models.DateTimeField(auto_now_add=True)),
                ('price_to', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.colors')),
                ('laminate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.laminate')),
                ('overprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.overprint')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.dimensions')),
                ('handle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.handletype')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.paper')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.printing')),
            ],
        ),
    ]
