# Generated by Django 3.2.9 on 2022-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torebki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dimensions',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='handletype',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laminate',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='overprint',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
