# Generated by Django 4.0.4 on 2022-04-26 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torebki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_num', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('overprint', models.CharField(choices=[('full', 'full'), ('not_full', 'not full')], default='not_full', max_length=50)),
            ],
        ),
    ]
