# Generated by Django 4.0.4 on 2022-04-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torebki', '0002_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='laminate',
            field=models.CharField(choices=[('glossy', 'glossy'), ('matte', 'matte')], default='glossy', max_length=50),
        ),
    ]
