# Generated by Django 4.0.4 on 2022-04-26 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torebki', '0003_printing_laminate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='colors_num',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_type', models.CharField(choices=[('string', 'string'), ('cutout', 'cutout')], default='string', max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.paper')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.printing')),
            ],
        ),
    ]
