# Generated by Django 4.0.4 on 2022-04-26 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torebki', '0004_alter_printing_colors_num_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.SmallIntegerField()),
                ('width', models.SmallIntegerField()),
                ('depth', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='printing',
            name='colors_num',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bag',
            name='dimensions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torebki.dimensions'),
        ),
    ]
